spring.application.name=Messenger

spring.datasource.url=jdbc:postgresql://localhost:5432/messenger
spring.datasource.username=postgres
spring.datasource.password=Test@123
spring.jpa.hibernate.ddl-auto=update